spring:
  # rabbitmq连接信息
  rabbitmq:
    addresses: 192.168.1.125
    port: 5672
    username: admin
    password: 123456

  #数据源
  datasource:
    class:
      url: jdbc:mysql://127.0.0.1:3306/jhwx_class_data?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
    driverClassName: com.mysql.jdbc.Driver
    password: root
    username: root

  #消息队列配置
  cloud:
    stream:
      bindings:
        statistical-watch-video-input:
          consumer:
            maxAttempts: 1
          destination: statistical-watch-video
          group: ${spring.application.name}
        statistical-watch-video-output:
          destination: statistical-watch-video
      rabbit:
        bindings:
          statistical-watch-video-input:
            consumer:
              autoBindDlq: true #开启死信队列
              dlqTtl: 86400000
              republishToDlq: true
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
