eureka:
    client:
        fetchRegistry: false
        registerWithEureka: false
        serviceUrl:
            defaultZone: http://jhwxadmin:jhwxadmin@localhost:40000/eureka/
    instance:
        hostname: ${spring.cloud.client.ip-address}
        instance-id: ${spring.cloud.client.ip-address}:${server.port}
        ip-address: true
spring:
    #配置绑定信息
    cloud:
        stream:
            bindings:
                statistical-watch-video-input:
                    destination: statistical-watch-video
                    group: ${spring.application.name}
                statistical-watch-video-output:
                    destination: statistical-watch-video
                    group: ${spring.application.name}
            rabbit:
                bindings:
                    statistical-watch-video-input:
                        consumer:
                            delayedExchange: true
                    statistical-watch-video-output:
                        producer:
                            delayedExchange: true
    #数据源相关配置
    datasource:
        class:
            url: jdbc:mysql://127.0.0.1:3306/jhwx_class_data?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
        driverClassName: com.mysql.jdbc.Driver
        password: root
        username: root

    #rabbitmq配置
    rabbitmq:
        addresses: 192.168.1.108
        password: 123456
        port: 5672
        username: admin
    sleuth:
        sampler:
            percentage: 1.0

    zipkin:
        base-url: http://${spring.cloud.client.ip-address}:40100/
