eureka:
  client:
    service-url:
      defaultZone: http://jhwx:jhwxadmin@${spring.cloud.client.ip-address}:40000/eureka/
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    ip-address: true
spring:
  # rabbitmq连接信息
  rabbitmq:
    addresses: 118.145.23.151
    port: 5672
    username: admin
    password: jhwxadmin
  #数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    class:
      url: jdbc:mysql://172.16.10.151:3306/jhwx_class_data?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
    gm:
      url: jdbc:mysql://172.16.10.151:3306/gm_database?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
    driverClassName: com.mysql.jdbc.Driver
    password: 360@(abc)
    username: root
    druid:
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filters: stat,wall,slf4j
      initial-size: 5
      max-active: 20
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      min-idle: 5
      pool-prepared-statements: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 30000

  #消息队列配置
  cloud:
    stream:
      bindings:
        statistical-watch-video-input:
          consumer:
            maxAttempts: 1
          destination: statistical-watch-video
          group: ${spring.application.name}
        statistical-watch-video-output:
          destination: statistical-watch-video
      rabbit:
        bindings:
          statistical-watch-video-input:
            consumer:
              autoBindDlq: true #开启死信队列
              republishToDlq: true
  zipkin:
    base-url: http://${spring.cloud.client.ip-address}:40020/
  sleuth:
    sampler:
      percentage: 1.0 #0.1-1.0 也就是代表链路跟踪的数据上传的概率有多大

